#include "osuKernel.h"

//
// Handles PnP Device Add
//
NTSTATUS OsuKernelEvtDeviceAdd(
    _In_    WDFDRIVER       Driver,
    _Inout_ PWDFDEVICE_INIT DeviceInit
)
{
    UNREFERENCED_PARAMETER(Driver);
    NTSTATUS status;
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    WDFDEVICE device;
    PDEVICE_CONTEXT devCtx;

    PAGED_CODE();

    // Set PNP / Power callbacks
    WDF_PNPPOWER_EVENT_CALLBACKS pnpPowerCallbacks;
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);
    pnpPowerCallbacks.EvtDevicePrepareHardware = OsuKernelEvtDevicePrepareHardware;
    pnpPowerCallbacks.EvtDeviceReleaseHardware = OsuKernelEvtDeviceReleaseHardware;
    pnpPowerCallbacks.EvtDeviceD0Entry = OsuKernelEvtDeviceD0Entry;
    pnpPowerCallbacks.EvtDeviceD0Exit = OsuKernelEvtDeviceD0Exit;
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);

    // Enable autogenerated device name to prevent STATUS_OBJECT_NAME_COLLISION (Code 31)
    WdfDeviceInitSetCharacteristics(DeviceInit, FILE_AUTOGENERATED_DEVICE_NAME, TRUE);

    // Grant World / Everyone full access so standard user apps (configurator, games) can open device
    DECLARE_CONST_UNICODE_STRING(sddlWorld, L"D:P(A;;GA;;;SY)(A;;GA;;;BA)(A;;GA;;;WD)(A;;GA;;;RC)");
    WdfDeviceInitAssignSDDLString(DeviceInit, &sddlWorld);

    // Allocate Device Context
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);
    if (!NT_SUCCESS(status)) {
        KdPrintDbg("WdfDeviceCreate failed: 0x%08X\n", status);
        return status;
    }

    devCtx = DeviceGetContext(device);
    RtlZeroMemory(devCtx, sizeof(DEVICE_CONTEXT));
    devCtx->Device = device;

    // Create primary symbolic link (\DosDevices\osuKernelDevice)
    DECLARE_CONST_UNICODE_STRING(primarySymLink, OSUKERNEL_DOS_DEVICE_NAME_W);
    IoDeleteSymbolicLink((PUNICODE_STRING)&primarySymLink);
    status = WdfDeviceCreateSymbolicLink(device, &primarySymLink);
    if (!NT_SUCCESS(status)) {
        KdPrintDbg("WdfDeviceCreateSymbolicLink osuKernelDevice failed: 0x%08X (continuing)\n", status);
    }

    // Register Device Interface GUID
    status = WdfDeviceCreateDeviceInterface(
        device,
        &GUID_DEVINTERFACE_OSUKERNEL,
        NULL
    );
    if (!NT_SUCCESS(status)) {
        KdPrintDbg("WdfDeviceCreateDeviceInterface failed: 0x%08X\n", status);
        return status;
    }

    // Initialize spinlocks
    WDF_OBJECT_ATTRIBUTES lockAttributes;
    WDF_OBJECT_ATTRIBUTES_INIT(&lockAttributes);
    lockAttributes.ParentObject = device;

    status = WdfSpinLockCreate(&lockAttributes, &devCtx->ConfigLock);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    status = WdfSpinLockCreate(&lockAttributes, &devCtx->StatsLock);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    // Set Default Active Area Mapping (Full Tablet -> Standard Full HD Screen)
    devCtx->AreaConfig.TabletInputX = 0;
    devCtx->AreaConfig.TabletInputY = 0;
    devCtx->AreaConfig.TabletInputWidth = OSUKERNEL_DEFAULT_MAX_X;   // 15200 counts (152mm)
    devCtx->AreaConfig.TabletInputHeight = OSUKERNEL_DEFAULT_MAX_Y;  // 9500 counts (95mm)
    devCtx->AreaConfig.ScreenOutputX = 0;
    devCtx->AreaConfig.ScreenOutputY = 0;
    devCtx->AreaConfig.ScreenOutputWidth = 1920;
    devCtx->AreaConfig.ScreenOutputHeight = 1080;
    devCtx->AreaConfig.AreaClipping = 1;
    devCtx->AreaConfig.AreaLimiting = 0;
    devCtx->AreaConfig.RotationAngle = 0;

    // Set Default Low-Latency Settings
    devCtx->Settings.LowLatencyMode = 1;
    devCtx->Settings.PressureCurveType = 0; // Linear
    devCtx->Settings.PressureGammaFixed = 65536; // 1.0 in 16.16
    devCtx->Settings.TipClickThreshold = 0;
    devCtx->Settings.RawPassthrough = 0;
    devCtx->Settings.EnableSmoothing = 0;   // Lowest latency: 0 filters
    devCtx->Settings.SmoothingStrength = 0;
    devCtx->Settings.AntichatterDeadzone = 0;
    devCtx->Settings.InterpolationRate = 0;
    devCtx->Settings.DisableTipClick = 0;
    devCtx->Settings.EnablePressure = 1;

    OsuKernelRecalculateScales(devCtx);

    // Initialize performance frequency and PPS counter timestamp correctly
    devCtx->LastPpsTimestamp = KeQueryPerformanceCounter(&devCtx->PerfFreq);
    devCtx->InterpCurrTime = devCtx->LastPpsTimestamp;
    devCtx->InterpPrevTime = devCtx->LastPpsTimestamp;

    // Create default I/O queue for IOCTLs
    WDF_IO_QUEUE_CONFIG queueConfig;
    WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queueConfig, WdfIoQueueDispatchSequential);
    queueConfig.EvtIoDeviceControl = OsuKernelEvtIoDeviceControl;

    WDFQUEUE queue;
    status = WdfIoQueueCreate(device, &queueConfig, WDF_NO_OBJECT_ATTRIBUTES, &queue);
    if (!NT_SUCCESS(status)) {
        KdPrintDbg("WdfIoQueueCreate failed: 0x%08X\n", status);
        return status;
    }

    KdPrintDbg("osuKernel Device initialized successfully.\n");
    return STATUS_SUCCESS;
}

//
// PnP Prepare Hardware - configure USB
//
NTSTATUS OsuKernelEvtDevicePrepareHardware(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated
)
{
    UNREFERENCED_PARAMETER(ResourcesRaw);
    UNREFERENCED_PARAMETER(ResourcesTranslated);
    PDEVICE_CONTEXT devCtx = DeviceGetContext(Device);

    PAGED_CODE();

    return OsuKernelConfigureUsb(Device, devCtx);
}

//
// PnP Release Hardware
//
NTSTATUS OsuKernelEvtDeviceReleaseHardware(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesTranslated
)
{
    UNREFERENCED_PARAMETER(ResourcesTranslated);
    PDEVICE_CONTEXT devCtx = DeviceGetContext(Device);

    PAGED_CODE();

    if (devCtx->UsbDevice != NULL) {
        devCtx->UsbDevice = NULL;
    }

    return STATUS_SUCCESS;
}

//
// Power D0 Entry - start continuous reader
//
NTSTATUS OsuKernelEvtDeviceD0Entry(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState
)
{
    UNREFERENCED_PARAMETER(PreviousState);
    PDEVICE_CONTEXT devCtx = DeviceGetContext(Device);
    NTSTATUS status = STATUS_SUCCESS;

    if (devCtx->InterruptPipe != NULL) {
        status = WdfIoTargetStart(WdfUsbTargetPipeGetIoTarget(devCtx->InterruptPipe));
        if (!NT_SUCCESS(status)) {
            KdPrintDbg("WdfIoTargetStart for Interrupt Pipe failed: 0x%08X\n", status);
        }
    }

    return status;
}

//
// Power D0 Exit - stop continuous reader
//
NTSTATUS OsuKernelEvtDeviceD0Exit(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE TargetState
)
{
    UNREFERENCED_PARAMETER(TargetState);
    PDEVICE_CONTEXT devCtx = DeviceGetContext(Device);

    if (devCtx->InterruptPipe != NULL) {
        WdfIoTargetStop(WdfUsbTargetPipeGetIoTarget(devCtx->InterruptPipe), WdfIoTargetCancelSentIo);
    }

    return STATUS_SUCCESS;
}
